GET http://localhost:8080/hello

###

GET http://localhost:8080/api/arzt

###

POST http://localhost:8080/api/arzt
Content-Type: application/json

{
  "id": 34,
  "name": "peter2",
  "profession": "chirurg"
}

###

GET http://localhost:8080/api/arzt